-- MySQL Script generated by MySQL Workbench
-- Mon May  5 23:20:00 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pharmacy_portal_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pharmacy_portal_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pharmacy_portal_db` DEFAULT CHARACTER SET utf8 ;
USE `pharmacy_portal_db` ;

-- -----------------------------------------------------
-- Table `pharmacy_portal_db`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy_portal_db`.`Users` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `contactInfo` VARCHAR(200) NULL,
  `userType` ENUM('pharmacist', 'patient') NOT NULL,
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC) VISIBLE,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy_portal_db`.`Medications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy_portal_db`.`Medications` (
  `medicationId` INT NOT NULL AUTO_INCREMENT,
  `medicationName` VARCHAR(45) NOT NULL,
  `dosage` VARCHAR(45) NOT NULL,
  `maufacturer` VARCHAR(100) NULL,
  UNIQUE INDEX `medicationId_UNIQUE` (`medicationId` ASC) VISIBLE,
  PRIMARY KEY (`medicationId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy_portal_db`.`Prescriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy_portal_db`.`Prescriptions` (
  `prescriptionId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `medicationId` INT NOT NULL,
  `prescribedDate` DATETIME NOT NULL,
  `dosageInstructions` VARCHAR(200) NULL,
  `quantity` INT NOT NULL,
  `refillCount` INT NOT NULL DEFAULT 0,
  UNIQUE INDEX `prescriptionId_UNIQUE` (`prescriptionId` ASC) VISIBLE,
  PRIMARY KEY (`prescriptionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy_portal_db`.`Inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy_portal_db`.`Inventory` (
  `inventoryId` INT NOT NULL AUTO_INCREMENT,
  `medicationId` INT NOT NULL,
  `quantityAvailable` INT NOT NULL,
  `lastUpdated` DATETIME NOT NULL,
  PRIMARY KEY (`inventoryId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy_portal_db`.`Sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy_portal_db`.`Sales` (
  `saleId` INT NOT NULL AUTO_INCREMENT,
  `prescriptionId` INT NOT NULL,
  `saleDate` DATETIME NOT NULL,
  `quantitySold` INT NOT NULL,
  `saleAmount` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`saleId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
